#version: '3.8'

services:
    nginx:
        image: 'nginx:stable-alpine'
        ports:
            - "8000:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www/block-app

    php:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - .:/var/www/block-app

    mysql:
        image: mysql:8.0
        ports:
            - "3336:3306"
        env_file:
            - env/mysql.env
        volumes:
            - mysqldata-volume:/var/lib/mysql

    composer:
        build:
            context: dockerfiles
            dockerfile: composer.Dockerfile
        volumes:
            - .:/var/www/block-app
    artisan:
        build:
            context: dockerfiles
            dockerfile: php.Dockerfile
        volumes:
            - .:/var/www/block-app
        working_dir: /var/www/block-app
        entrypoint: [ "php", "artisan" ]

volumes:
    mysqldata-volume:
